version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: solarsense-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: solarsense
    volumes:
      - mongodb_data:/data/db
    networks:
      - solarsense-network

  redis:
    image: redis:7.2-alpine
    container_name: solarsense-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - solarsense-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: solarsense-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/solarsense?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
      - redis
    networks:
      - solarsense-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: solarsense-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - solarsense-network

volumes:
  mongodb_data:
  redis_data:

networks:
  solarsense-network:
    driver: bridge
