# Render deployment configuration for SolarSense Backend
services:
  - type: web
    name: solarsense-backend
    env: node
    plan: free
    buildCommand: npm run install:all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
      - key: STRIPE_PUBLISHABLE_KEY
        value: ${STRIPE_PUBLISHABLE_KEY}
      - key: STRIPE_WEBHOOK_SECRET
        value: ${STRIPE_WEBHOOK_SECRET}

# Using MongoDB Atlas - no local database needed
